### ISSUE TITLE
Similarities in LibraryCatalogue and LibraryMember class

### ISSUE THREAD

**Issue by ghost** [andela-ekarumbi/BookClub#9]
There are instances where there's duplicity of code blocks in your LibraryCatalogue and LibraryMember classes. Identify these code blocks and refactor duly.

**Comment by doc2dev** [comment]
For the life of me, I can't figure out the duplicity. Will consult further.

**Comment by doc2dev** [comment]
Class `LibraryStorage<T extends Model>` has been created to abstract the functions provided by classes `LibraryCatalogue` and `LibraryMembers`, and the two classes have been deleted. The methods previously exposed by those two classes are now exposed by class `Library`, as wrappers over instances of class `LibraryStorage`.

**Comment by doc2dev** [comment]
The issue is fully resolved now.
